#!/usr/bin/env ruby

ROOT = File.expand_path(File.dirname(__FILE__) + '/../')

require File.expand_path(File.join(ROOT, 'vendor', 'gems', 'environment'))
Bundler.require_env("daemon")

require 'eventmachine'
require 'daemons'

require "#{ROOT}/bookit"

ENV['APP_ENV'] = ARGV[1] || "development" unless ENV['APP_ENV']
include AutomateAT::Daemon

def stop
  EventMachine::stop_event_loop
end

Signal.trap("TERM") {stop}
Signal.trap("INT") {stop}

Daemons.run_proc("bookit", {:monitor => false, :dir_mode => :normal, :dir => "#{ROOT}/log",
                            :multiple => false, :backtrace=>true}) do
  EM.run{
    start
  }
end