#!/usr/bin/env ruby
require "#{File.expand_path(File.dirname(__FILE__) + '/../')}/bookit"

Bundler.require("daemon")

require 'eventmachine'
require 'daemons'

include AutomateAT::Daemon

def stop
  EventMachine::stop_event_loop
end

Signal.trap("TERM") {stop}
Signal.trap("INT") {stop}

Daemons.run_proc("bookit", {:monitor => false, :dir_mode => :normal, :dir => "#{ROOT}/log",
                            :multiple => false, :backtrace=>true}) do
  EM.run{
    start
  }
end